var height = 500;
var width = 500;
var padding = 20;
var yScale = d3.scaleLinear()
    .domain(d3.extent(birthData2011, d=>d.lifeExpectancy))
    .range([height-padding, padding]);
var xScale = d3.scaleLinear()
    .domain(d3.extent(birthData2011, d => d.births / d.population))
    .range([padding, width - padding]);
var xAxis = d3.axisBottom(xScale)
    .tickSize(-height+ 2*padding)
    .tickSizeOuter(0)
var yAxis = d3.axisLeft(yScale)
    //set the size of the gride line
    .tickSize(-width+ 2*padding)
    //clean out the outer line
    .tickSizeOuter(0)
    
var colorScale = d3.scaleLinear()
    .domain(d3.extent(birthData2011, d=> d.population/d.area))
    .range(['lightblue', 'red'])
var sizeScale = d3.scaleLinear()
    .domain(d3.extent(birthData2011, d=> d.births))
    .range([2,40])
d3.select('svg') 
    .append('g')
        .attr('transform', 'translate(0, ' + (height-padding) +')')
        .call(xAxis)
d3.select('svg') 
    .append('g')
        .attr('transform', 'translate(' + (padding) +', 0)')
        .call(yAxis)
d3.select('svg')
        .attr('width', width+padding)
        .attr('height', height+padding)
    .selectAll('circle')
    .data(birthData2011)
    .enter()
    .append('circle')
        .attr('cy', d=> yScale(d.lifeExpectancy))
        .attr('cx', d=> xScale(d.births/d.population))
        .attr('r', d=> sizeScale(d.births))
        .attr('fill', d=> colorScale(d.population/d.area))
d3.select('svg')
    .append('text')
        .attr('x', width/2)
        .attr('y', height -padding)
        .attr('dy', '1.5em')
        .style('text-anchor', 'middle')
        .text('Briths per Capita')
d3.select('svg')
    .append('text')
        .attr('x', width/2)
        .attr('y', padding)       
        .style('font-size', "1.5em")
        .style('text-anchor', 'middle')
        .text('Data on Births by Country in 2011')
d3.select('svg')
    .append('text')
        .attr('transform', 'rotate(90)')
        .attr('x', height/2)
        .attr('y', padding)
        .attr('dy', '-1.1em')
        .style('text-anchor', 'middle')
        .text('Life Expectancy')